export const FETCH_ANIME = "FETCH_ANIME";
export const FETCH_ANIME_SUCCESS = "FETCH_ANIME_SUCCESS";
export const FETCH_ANIME_DETAIL = "FETCH_ANIME_DETAIL";
export const FETCH_ANIME_DETAIL_SUCCESS = "FETCH_ANIME_DETAIL_SUCCESS";
export const SEARCH_ANIME = "SEARCH_ANIME";
export const SEARCH_ANIME_SUCCESS = "SEARCH_ANIME_SUCCESS";
export const FETCH_STUDIO_ANIME = "FETCH_STUDIO_ANIME";
export const FETCH_ANIME_GENRE = "FETCH_ANIME_GENRE";
export const FETCH_STUDIO_ANIME_SUCCESS = "FETCH_STUDIO_ANIME_SUCCESS";

// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

//alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

//profile
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILES = "GET_PROFILES";
export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";
export const CREATE_PROFILE = "CREATE_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const WATCHLIST_ADD = "WATCHLIST_ADD";
export const WATCHLIST_ADD_SUCCESS = "WATCHLIST_ADD_SUCCESS";
export const WATCHLIST_REMOVE = "WATCHLIST_REMOVE";
export const WATCHLIST_REMOVE_SUCCESS = "WATCHLIST_REMOVE_SUCCESS";
export const GET_PROFILE_BY_ID = "GET_PROFILE_BY_ID";

//post
export const SET_LIST_ALERT = "SET_LIST_ALERT";
export const ADD_POST = "ADD_POST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_POST_BY_ID = "GET_POST_BY_ID";
export const GET_POST_BY_ID_SUCCESS = "GET_POST_BY_ID_SUCCESS";
